USE [YourDatabaseName]
GO
/****** Object:  Table [dbo].[City]    Script Date: 11.02.2019 10:31:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_dbo.City] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Town]    Script Date: 11.02.2019 10:31:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Town](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CityId] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_dbo.Town] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[City] ON 
INSERT [dbo].[City] ([Id], [Name]) VALUES (1, N'Adana')
INSERT [dbo].[City] ([Id], [Name]) VALUES (2, N'Adıyaman')
INSERT [dbo].[City] ([Id], [Name]) VALUES (3, N'Afyon')
INSERT [dbo].[City] ([Id], [Name]) VALUES (4, N'Ağrı')
INSERT [dbo].[City] ([Id], [Name]) VALUES (5, N'Amasya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (6, N'Ankara')
INSERT [dbo].[City] ([Id], [Name]) VALUES (7, N'Antalya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (8, N'Artvin')
INSERT [dbo].[City] ([Id], [Name]) VALUES (9, N'Aydın')
INSERT [dbo].[City] ([Id], [Name]) VALUES (10, N'Balikesir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (11, N'Bilecik')
INSERT [dbo].[City] ([Id], [Name]) VALUES (12, N'Bingöl')
INSERT [dbo].[City] ([Id], [Name]) VALUES (13, N'Bitlis')
INSERT [dbo].[City] ([Id], [Name]) VALUES (14, N'Bolu')
INSERT [dbo].[City] ([Id], [Name]) VALUES (15, N'Burdur')
INSERT [dbo].[City] ([Id], [Name]) VALUES (16, N'Bursa')
INSERT [dbo].[City] ([Id], [Name]) VALUES (17, N'Çanakkale')
INSERT [dbo].[City] ([Id], [Name]) VALUES (18, N'Çankırı')
INSERT [dbo].[City] ([Id], [Name]) VALUES (19, N'Çorum')
INSERT [dbo].[City] ([Id], [Name]) VALUES (20, N'Denizli')
INSERT [dbo].[City] ([Id], [Name]) VALUES (21, N'Diyarbakir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (22, N'Edirne')
INSERT [dbo].[City] ([Id], [Name]) VALUES (23, N'Elazığ')
INSERT [dbo].[City] ([Id], [Name]) VALUES (24, N'Erzincan')
INSERT [dbo].[City] ([Id], [Name]) VALUES (25, N'Erzurum')
INSERT [dbo].[City] ([Id], [Name]) VALUES (26, N'Eskişehir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (27, N'Gaziantep')
INSERT [dbo].[City] ([Id], [Name]) VALUES (28, N'Giresun')
INSERT [dbo].[City] ([Id], [Name]) VALUES (29, N'Gümüşhane')
INSERT [dbo].[City] ([Id], [Name]) VALUES (30, N'Hakkari')
INSERT [dbo].[City] ([Id], [Name]) VALUES (31, N'Hatay')
INSERT [dbo].[City] ([Id], [Name]) VALUES (32, N'Isparta')
INSERT [dbo].[City] ([Id], [Name]) VALUES (33, N'Mersin')
INSERT [dbo].[City] ([Id], [Name]) VALUES (34, N'İstanbul')
INSERT [dbo].[City] ([Id], [Name]) VALUES (35, N'İzmir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (36, N'Kars')
INSERT [dbo].[City] ([Id], [Name]) VALUES (37, N'Kastamonu')
INSERT [dbo].[City] ([Id], [Name]) VALUES (38, N'Kayseri')
INSERT [dbo].[City] ([Id], [Name]) VALUES (39, N'Kırklareli')
INSERT [dbo].[City] ([Id], [Name]) VALUES (40, N'Kırşehir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (41, N'Kocaeli')
INSERT [dbo].[City] ([Id], [Name]) VALUES (42, N'Konya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (43, N'Kütahya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (44, N'Malatya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (45, N'Manisa')
INSERT [dbo].[City] ([Id], [Name]) VALUES (46, N'KahramanMaraş')
INSERT [dbo].[City] ([Id], [Name]) VALUES (47, N'Mardin')
INSERT [dbo].[City] ([Id], [Name]) VALUES (48, N'Muğla')
INSERT [dbo].[City] ([Id], [Name]) VALUES (49, N'Muş')
INSERT [dbo].[City] ([Id], [Name]) VALUES (50, N'Nevşehir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (51, N'Niğde')
INSERT [dbo].[City] ([Id], [Name]) VALUES (52, N'Ordu')
INSERT [dbo].[City] ([Id], [Name]) VALUES (53, N'Rize')
INSERT [dbo].[City] ([Id], [Name]) VALUES (54, N'Sakarya')
INSERT [dbo].[City] ([Id], [Name]) VALUES (55, N'Samsun')
INSERT [dbo].[City] ([Id], [Name]) VALUES (56, N'Siirt')
INSERT [dbo].[City] ([Id], [Name]) VALUES (57, N'Sinop')
INSERT [dbo].[City] ([Id], [Name]) VALUES (58, N'Sivas')
INSERT [dbo].[City] ([Id], [Name]) VALUES (59, N'Tekirdağ')
INSERT [dbo].[City] ([Id], [Name]) VALUES (60, N'Tokat')
INSERT [dbo].[City] ([Id], [Name]) VALUES (61, N'Trabzon')
INSERT [dbo].[City] ([Id], [Name]) VALUES (62, N'Tunceli')
INSERT [dbo].[City] ([Id], [Name]) VALUES (63, N'Şanlıurfa')
INSERT [dbo].[City] ([Id], [Name]) VALUES (64, N'Uşak')
INSERT [dbo].[City] ([Id], [Name]) VALUES (65, N'Van')
INSERT [dbo].[City] ([Id], [Name]) VALUES (66, N'Yozgat')
INSERT [dbo].[City] ([Id], [Name]) VALUES (67, N'Zonguldak')
INSERT [dbo].[City] ([Id], [Name]) VALUES (68, N'Aksaray')
INSERT [dbo].[City] ([Id], [Name]) VALUES (69, N'Bayburt')
INSERT [dbo].[City] ([Id], [Name]) VALUES (70, N'Karaman')
INSERT [dbo].[City] ([Id], [Name]) VALUES (71, N'Kırıkkale')
INSERT [dbo].[City] ([Id], [Name]) VALUES (72, N'Batman')
INSERT [dbo].[City] ([Id], [Name]) VALUES (73, N'Şırnak')
INSERT [dbo].[City] ([Id], [Name]) VALUES (74, N'Bartın')
INSERT [dbo].[City] ([Id], [Name]) VALUES (75, N'Ardahan')
INSERT [dbo].[City] ([Id], [Name]) VALUES (76, N'Iğdir')
INSERT [dbo].[City] ([Id], [Name]) VALUES (77, N'Yalova')
INSERT [dbo].[City] ([Id], [Name]) VALUES (78, N'Karabük')
INSERT [dbo].[City] ([Id], [Name]) VALUES (79, N'Kilis')
INSERT [dbo].[City] ([Id], [Name]) VALUES (80, N'Osmaniye')
INSERT [dbo].[City] ([Id], [Name]) VALUES (81, N'Düzce')
SET IDENTITY_INSERT [dbo].[City] OFF
SET IDENTITY_INSERT [dbo].[Town] ON 

INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (1, 1, N'Çukurova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (2, 1, N'Girne')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (3, 2, N'Gölbaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (4, 2, N'Tut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (5, 3, N'Bayat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (6, 3, N'Çobanlar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (7, 3, N'Şuhut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (8, 4, N'Eleşkirt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (9, 4, N'Hamur')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (10, 4, N'Patnos')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (11, 5, N'Gümüşhacıköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (12, 5, N'Merzifon')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (13, 6, N'Evren')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (14, 6, N'Güdül')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (15, 6, N'Kazan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (16, 6, N'Pursaklar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (17, 7, N'Aksu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (18, 7, N'Demre(Kale)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (19, 7, N'Gazipaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (20, 7, N'Kaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (21, 7, N'Konyaaltı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (22, 7, N'Muratpaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (23, 8, N'Arhavi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (24, 8, N'Borçka')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (25, 8, N'Hopa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (26, 9, N'Buharkent(Çubukdağı)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (27, 9, N'Çine')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (28, 9, N'İncirliova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (29, 9, N'Karacasu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (30, 9, N'Karpuzlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (31, 9, N'Köşk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (32, 9, N'Nazilli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (33, 9, N'Sultanhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (34, 10, N'Ayvalık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (35, 10, N'Balya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (36, 10, N'Burhaniye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (37, 10, N'Edremit')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (38, 10, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (39, 10, N'Sındırgı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (40, 11, N'Gölpazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (41, 11, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (42, 12, N'Adaklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (43, 12, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (44, 12, N'Yedisu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (45, 13, N'Adilçevaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (46, 13, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (47, 14, N'Dörtdivan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (48, 14, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (49, 15, N'Altınyayla(Dirmil)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (50, 16, N'Büyükorhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (51, 16, N'Gemlik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (52, 16, N'Mustafakemalpaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (53, 16, N'Nilüfer')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (54, 17, N'Bayramiç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (55, 17, N'Eceabat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (56, 17, N'Yenice')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (57, 18, N'Atkaracalar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (58, 18, N'Bayramören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (59, 18, N'Çerkeş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (60, 18, N'Yapraklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (61, 19, N'Bayat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (62, 19, N'İskilip')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (63, 19, N'Osmancık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (64, 19, N'Uğurludağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (65, 20, N'Baklan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (66, 20, N'Çal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (67, 20, N'Güney')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (68, 20, N'Tavas')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (69, 21, N'Çınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (70, 21, N'Çüngüş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (71, 21, N'Dicle')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (72, 21, N'Lice')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (73, 21, N'Sur')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (74, 21, N'Yenişehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (75, 22, N'Keşan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (76, 22, N'Süloğlu(Süleoğlu)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (77, 23, N'Alacakaya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (78, 23, N'Kovancılar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (79, 24, N'Kemaliye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (80, 25, N'Karaçoban')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (81, 25, N'Narman')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (82, 25, N'Oltu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (83, 25, N'Olur')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (84, 25, N'Tekman')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (85, 25, N'Tortum')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (86, 25, N'Uzundere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (87, 26, N'Çifteler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (88, 26, N'Han')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (89, 26, N'Mihalgazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (90, 26, N'Mihalıççık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (91, 26, N'Tepebaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (92, 27, N'İslahiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (93, 27, N'Yavuzeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (94, 28, N'Alucra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (95, 28, N'Bulancak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (96, 28, N'Çanakçı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (97, 28, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (98, 28, N'Yağlıdere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (99, 29, N'Merkez')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (100, 29, N'Torul')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (101, 30, N'Çukurca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (102, 30, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (103, 32, N'Atabey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (104, 32, N'Sütçüler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (105, 32, N'Uluborlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (106, 33, N'Akdeniz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (107, 33, N'Aydıncık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (108, 33, N'Bozyazı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (109, 34, N'Adalar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (110, 34, N'Avcılar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (111, 34, N'Beykoz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (112, 34, N'Çatalca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (113, 34, N'Esenler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (114, 34, N'Eyüp')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (115, 34, N'Fatih')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (116, 34, N'Gaziosmanpaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (117, 34, N'Kağıthane')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (118, 34, N'Kartal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (119, 34, N'Pendik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (120, 34, N'Sarıyer')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (121, 34, N'Sultangazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (122, 34, N'Tuzla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (123, 34, N'Zeytinburnu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (124, 35, N'Balçova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (125, 35, N'Bayındır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (126, 35, N'Çiğli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (127, 35, N'Güzelbahçe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (128, 35, N'Karabağlar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (129, 35, N'Karaburun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (130, 35, N'Kemalpaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (131, 35, N'Konak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (132, 35, N'Ödemiş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (133, 35, N'Tire')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (134, 36, N'Arpaçay')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (135, 37, N'Azdavay')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (136, 37, N'Hanönü(Gökçeağaç)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (137, 37, N'İnebolu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (138, 38, N'Hacılar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (139, 39, N'Demirköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (140, 39, N'Kofçaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (141, 39, N'Pehlivanköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (142, 39, N'Vize')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (143, 40, N'Akpınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (144, 40, N'Boztepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (145, 41, N'Dilovası')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (146, 41, N'Körfez(Tütünçiftlik)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (147, 42, N'Çağlıyancerit')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (148, 42, N'Nurhak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (149, 43, N'Akören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (150, 43, N'Çumra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (151, 43, N'Derbent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (152, 43, N'Doğanhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (153, 43, N'Emirgazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (154, 43, N'Ereğli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (155, 43, N'ilgın')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (156, 43, N'Sarayönü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (157, 44, N'Çavdarhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (158, 44, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (159, 44, N'Tavşanlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (160, 45, N'Akçadağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (161, 45, N'Doğanşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (162, 45, N'Kuluncak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (163, 45, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (164, 46, N'Gölmarmara')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (165, 46, N'Gördes')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (166, 46, N'Kula')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (167, 46, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (168, 46, N'Sarıgöl')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (169, 46, N'Selendi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (170, 46, N'Soma')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (171, 47, N'Dargeçit')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (172, 47, N'Derik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (173, 47, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (174, 48, N'Köyceğiz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (175, 48, N'Milas')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (176, 49, N'Hasköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (177, 49, N'Malazgirt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (178, 50, N'Avanos')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (179, 50, N'Kozaklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (180, 51, N'Çamardı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (181, 51, N'Ulukışla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (182, 52, N'Akkuş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (183, 52, N'Çatalpınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (184, 52, N'Çaybaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (185, 52, N'Gülyalı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (186, 53, N'Derepazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (187, 54, N'Arifiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (188, 54, N'Hendek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (189, 54, N'Karasu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (190, 54, N'Kaynarca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (191, 54, N'Sapanca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (192, 54, N'Serdivan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (193, 55, N'Canik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (194, 55, N'Çarşamba')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (195, 55, N'Terme')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (196, 55, N'Vezirköprü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (197, 56, N'Aydınlar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (198, 56, N'Baykan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (199, 57, N'Ayancık')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (200, 57, N'Boyabat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (201, 57, N'Durağan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (202, 58, N'Gürün')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (203, 58, N'Kangal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (204, 58, N'Koyulhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (205, 59, N'Çorlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (206, 60, N'Almus')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (207, 60, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (208, 60, N'Pazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (209, 60, N'ReşNameye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (210, 61, N'Beşikdüzü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (211, 61, N'Düzköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (212, 61, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (213, 61, N'Tonya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (214, 62, N'Hozat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (215, 62, N'Mazgirt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (216, 62, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (217, 62, N'Pülümür')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (218, 63, N'Halfeti')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (219, 63, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (220, 63, N'Siverek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (221, 64, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (222, 65, N'Çatak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (223, 65, N'Edremit(Gümüşdere)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (224, 65, N'Erciş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (225, 65, N'Gevaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (226, 65, N'Gürpınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (227, 65, N'Saray')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (228, 66, N'Akdağmadeni')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (229, 1, N'Karaisalı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (230, 1, N'Karataş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (231, 1, N'Seyhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (232, 1, N'Yumurtalık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (233, 2, N'Besni')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (234, 2, N'Çelikhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (235, 2, N'Gerger')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (236, 2, N'Samsat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (237, 3, N'Başmakçı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (238, 3, N'BolvNamen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (239, 3, N'Dazkırı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (240, 3, N'Emirdağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (241, 3, N'Evciler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (242, 3, N'İscehisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (243, 3, N'Kızılören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (244, 3, N'Sandıklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (245, 4, N'DiyNamen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (246, 4, N'Tutak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (247, 5, N'Hamamözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (248, 6, N'Çubuk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (249, 6, N'Etimesgut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (250, 6, N'Gölbaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (251, 6, N'Haymana')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (252, 6, N'Mamak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (253, 6, N'Polatlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (254, 7, N'Döşemealtı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (255, 7, N'Finike')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (256, 7, N'Manavgat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (257, 9, N'Kuşadası')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (258, 9, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (259, 9, N'Söke')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (260, 9, N'Yenipazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (261, 10, N'Havran')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (262, 10, N'Kepsut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (263, 10, N'Marmara')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (264, 10, N'Savaştepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (265, 12, N'Genç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (266, 13, N'Güroymak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (267, 14, N'Göynük')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (268, 14, N'Kıbrıscık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (269, 14, N'Mengen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (270, 15, N'Çavdır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (271, 15, N'Kemer')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (272, 16, N'İnegöl')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (273, 16, N'Keles')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (274, 16, N'Mudanya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (275, 16, N'Orhaneli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (276, 16, N'Orhangazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (277, 16, N'Yenişehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (278, 16, N'Yıldırım')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (279, 17, N'Ayvacık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (280, 17, N'Bozcaada')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (281, 17, N'Ezine')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (282, 17, N'Gelibolu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (283, 17, N'Lapseki')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (284, 18, N'Eldivan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (285, 18, N'ilgaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (286, 18, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (287, 19, N'Dodurga')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (288, 19, N'Kargı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (289, 19, N'Mecitözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (290, 20, N'Babadağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (291, 20, N'Buldan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (292, 20, N'Sarayköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (293, 20, N'Serinhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (294, 21, N'Bismil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (295, 21, N'Silvan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (296, 22, N'Havsa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (297, 23, N'Baskil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (298, 23, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (299, 23, N'Palu')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (300, 23, N'Sivrice')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (301, 24, N'Üzümlü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (302, 25, N'Horasan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (303, 25, N'İspir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (304, 25, N'Pasinler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (305, 25, N'Şenkaya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (306, 26, N'Alpu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (307, 26, N'Günyüzü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (308, 26, N'Sarıcakaya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (309, 27, N'Karkamış')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (310, 27, N'Nizip')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (311, 27, N'Oğuzeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (312, 27, N'Şahinbey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (313, 28, N'Dereli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (314, 28, N'Eynesil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (315, 28, N'Güce')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (316, 28, N'Keşap')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (317, 29, N'Köse')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (318, 29, N'Kürtün')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (319, 31, N'İskenderun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (320, 31, N'Kumlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (321, 32, N'Gönen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (322, 32, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (323, 33, N'Çamlıyayla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (324, 33, N'Erdemli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (325, 33, N'Mut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (326, 33, N'Toroslar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (327, 34, N'Arnavutköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (328, 34, N'Bağcılar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (329, 34, N'Bayrampaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (330, 34, N'Esenyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (331, 34, N'Maltepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (332, 34, N'Silivri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (333, 34, N'Şişli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (334, 34, N'Üsküdar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (335, 35, N'Bayraklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (336, 35, N'Dikili')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (337, 35, N'Seferihisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (338, 36, N'Kağızman')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (339, 36, N'Susuz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (340, 37, N'Araç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (341, 37, N'Bozkurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (342, 37, N'CIde')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (343, 37, N'Çatalzeytin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (344, 37, N'Daday')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (345, 37, N'Devrekani')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (346, 37, N'Doğanyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (347, 37, N'İhsangazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (348, 37, N'Küre')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (349, 37, N'Seydiler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (350, 37, N'Taşköprü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (351, 38, N'Akkışla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (352, 38, N'Bünyan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (353, 38, N'Tomarza')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (354, 38, N'Yahyalı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (355, 39, N'Lüleburgaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (356, 40, N'Kaman')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (357, 41, N'Darıca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (358, 41, N'Derince')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (359, 41, N'Gebze')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (360, 41, N'Karamürsel')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (361, 42, N'Andırın')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (362, 42, N'Ekinözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (363, 43, N'Bozkır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (364, 43, N'Güneysınır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (365, 43, N'HNamem')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (366, 43, N'Hüyük')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (367, 43, N'Seydişehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (368, 43, N'Yunak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (369, 44, N'Domaniç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (370, 45, N'Arapkir(Arapgir)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (371, 45, N'Battalgazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (372, 45, N'Hekimhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (373, 45, N'Yeşilyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (374, 46, N'Ahmetli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (375, 46, N'Demirci')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (376, 46, N'Salihli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (377, 47, N'Mazıdağı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (378, 48, N'Dalaman')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (379, 48, N'Datça')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (380, 48, N'Kavaklıdere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (381, 48, N'Marmaris')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (382, 48, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (383, 48, N'Ortaca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (384, 49, N'Bulanık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (385, 49, N'Varto')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (386, 50, N'Derinkuyu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (387, 50, N'Gülşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (388, 50, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (389, 51, N'Çiftlik(Özyurt)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (390, 52, N'Aybastı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (391, 52, N'Fatsa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (392, 52, N'İkizce')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (393, 52, N'Kumru')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (394, 52, N'Ulubey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (395, 53, N'Çamlıhemşin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (396, 54, N'Akyazı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (397, 54, N'Geyve')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (398, 54, N'Pamukova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (399, 55, N'Asarcık')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (400, 55, N'Havza')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (401, 55, N'ilkadım')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (402, 55, N'Ondokuzmayıs(Ballıca)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (403, 55, N'Salıpazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (404, 57, N'Dikmen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (405, 57, N'Erfelek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (406, 57, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (407, 57, N'Saraydüzü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (408, 58, N'Gemerek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (409, 58, N'Gölova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (410, 58, N'Hafik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (411, 58, N'Suşehri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (412, 58, N'Şarkışla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (413, 58, N'Yıldızeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (414, 59, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (415, 59, N'Şarköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (416, 60, N'Artova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (417, 60, N'Erbaa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (418, 60, N'Niksar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (419, 60, N'Sulusaray')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (420, 61, N'Çarşıbaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (421, 61, N'Çaykara')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (422, 61, N'Sürmene')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (423, 61, N'Vakfıkebir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (424, 62, N'Çemişgezek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (425, 62, N'Ovacık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (426, 65, N'MurNameye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (427, 66, N'Kadışehri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (428, 66, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (429, 66, N'Şefaatli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (430, 66, N'Yenifakılı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (431, 67, N'Gökçebey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (432, 68, N'Ağaçören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (433, 68, N'Gülağaç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (434, 68, N'Güzelyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (435, 68, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (436, 68, N'Ortaköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (437, 70, N'Ayrancı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (438, 70, N'Başyayla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (439, 70, N'Ermenek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (440, 71, N'Delice')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (441, 71, N'Keskin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (442, 72, N'Beşiri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (443, 73, N'Cizre')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (444, 73, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (445, 74, N'Amasra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (446, 74, N'Kurucaşile')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (447, 75, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (448, 77, N'Armutlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (449, 78, N'Ovacık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (450, 78, N'Yenice')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (451, 81, N'Akçakoca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (452, 81, N'Kaynaşlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (453, 81, N'Yığılca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (454, 1, N'Aladağ(Karsantı)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (455, 1, N'Ceyhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (456, 1, N'Feke')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (457, 1, N'İmamoğlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (458, 1, N'Kozan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (459, 1, N'Tufanbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (460, 2, N'Kahta')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (461, 2, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (462, 2, N'Sincik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (463, 3, N'Çay')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (464, 3, N'Dinar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (465, 3, N'Hocalar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (466, 3, N'İhsaniye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (467, 3, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (468, 3, N'Sultandağı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (469, 4, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (470, 4, N'Taşlıçay')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (471, 5, N'Göynücek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (472, 5, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (473, 5, N'Suluova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (474, 5, N'Taşova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (475, 6, N'Akyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (476, 6, N'Ayaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (477, 6, N'Çankaya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (478, 6, N'Elmadağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (479, 6, N'Nallıhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (480, 6, N'Sincan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (481, 7, N'Akseki')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (482, 7, N'Alanya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (483, 7, N'İbradı(Aydınkent)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (484, 7, N'Kepez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (485, 7, N'Korkuteli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (486, 7, N'Kumluca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (487, 7, N'Serik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (488, 8, N'Murgul(Göktaş)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (489, 8, N'Yusufeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (490, 9, N'Bozdoğan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (491, 9, N'Germencik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (492, 9, N'Kuyucak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (493, 10, N'Bandırma')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (494, 10, N'BigNameç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (495, 10, N'Gömeç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (496, 11, N'Bozüyük')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (497, 11, N'İnhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (498, 11, N'Pazaryeri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (499, 11, N'Söğüt')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (500, 11, N'Yenipazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (501, 12, N'Yayladere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (502, 13, N'Hizan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (503, 13, N'Mutki')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (504, 14, N'Mudurnu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (505, 15, N'Ağlasun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (506, 15, N'Bucak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (507, 15, N'Çeltikçi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (508, 15, N'Yeşilova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (509, 16, N'İznik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (510, 16, N'Karacabey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (511, 16, N'Osmangazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (512, 17, N'Biga')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (513, 18, N'Kızılırmak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (514, 18, N'Şabanözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (515, 19, N'Alaca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (516, 19, N'Laçin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (517, 19, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (518, 19, N'Oğuzlar(Karaören)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (519, 19, N'Sungurlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (520, 20, N'Acıpayam')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (521, 20, N'Beyağaç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (522, 20, N'Çardak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (523, 20, N'Honaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (524, 20, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (525, 21, N'Çermik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (526, 21, N'Eğil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (527, 21, N'Ergani')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (528, 21, N'Hazro')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (529, 21, N'Kayapınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (530, 21, N'Kulp')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (531, 22, N'İpsala')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (532, 22, N'Meriç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (533, 22, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (534, 22, N'Uzunköprü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (535, 24, N'Çayırlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (536, 24, N'Kemah')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (537, 24, N'Tercan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (538, 25, N'Aşkale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (539, 25, N'Aziziye(ilıca)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (540, 25, N'Çat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (541, 25, N'Karayazı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (542, 25, N'Köprüköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (543, 25, N'Palandöken')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (544, 25, N'Yakutiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (545, 26, N'Beylikova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (546, 26, N'İnönü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (547, 26, N'Mahmudiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (548, 27, N'Nurdağı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (549, 28, N'Doğankent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (550, 28, N'Görele')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (551, 30, N'Yüksekova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (552, 31, N'Dörtyol')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (553, 31, N'Hassa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (554, 31, N'Reyhanlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (555, 31, N'Samandağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (556, 31, N'Yayladağı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (557, 32, N'Aksu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (558, 32, N'Eğirdir(EğrIdir)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (559, 32, N'Gelendost')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (560, 32, N'Keçiborlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (561, 32, N'Senirkent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (562, 32, N'Şarkikaraağaç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (563, 32, N'Yalvaç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (564, 33, N'Anamur')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (565, 33, N'Gülnar (Gülpınar)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (566, 33, N'Silifke')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (567, 34, N'Bakırköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (568, 34, N'Başakşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (569, 34, N'Beşiktaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (570, 34, N'Beylikdüzü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (571, 34, N'Büyükçekmece')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (572, 34, N'Kadıköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (573, 34, N'Sancaktepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (574, 34, N'Sultanbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (575, 35, N'Aliağa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (576, 35, N'Beydağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (577, 35, N'Buca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (578, 35, N'Çeşme')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (579, 35, N'Foça')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (580, 35, N'Gaziemir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (581, 35, N'Kınık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (582, 35, N'Kiraz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (583, 35, N'Torbalı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (584, 35, N'Urla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (585, 36, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (586, 37, N'Abana')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (587, 37, N'Ağlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (588, 37, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (589, 37, N'Pınarbaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (590, 37, N'Tosya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (591, 38, N'Felahiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (592, 38, N'İncesu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (593, 38, N'Kocasinan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (594, 38, N'Pınarbaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (595, 38, N'Sarız')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (596, 38, N'Talas')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (597, 39, N'Babaeski')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (598, 39, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (599, 40, N'Mucur')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (600, 42, N'Afşin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (601, 42, N'Elbistan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (602, 42, N'Pazarcık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (603, 43, N'Akşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (604, 43, N'Altınekin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (605, 43, N'Cihanbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (606, 43, N'Çeltik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (607, 43, N'Derebucak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (608, 43, N'Kadınhanı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (609, 43, N'Karapınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (610, 43, N'Kulu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (611, 43, N'Selçuklu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (612, 43, N'Yalıhüyük')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (613, 44, N'Dumlupınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (614, 44, N'Emet')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (615, 44, N'Gediz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (616, 44, N'Hisarcık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (617, 44, N'Pazarlar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (618, 44, N'Şaphane')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (619, 45, N'Darende')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (620, 45, N'Pütürge(Pötürge)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (621, 45, N'Yazıhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (622, 46, N'Köprübaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (623, 46, N'Saruhanlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (624, 47, N'Kızıltepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (625, 48, N'Bodrum')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (626, 50, N'Acıgöl')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (627, 51, N'Altunhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (628, 52, N'Gölköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (629, 52, N'Gürgentepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (630, 52, N'Kabadüz(Karadüz)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (631, 52, N'Korgan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (632, 52, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (633, 52, N'Mesudiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (634, 52, N'Ünye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (635, 53, N'Ardeşen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (636, 53, N'Çayeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (637, 53, N'Fındıklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (638, 53, N'Hemşin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (639, 53, N'İyIdere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (640, 53, N'Kalkandere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (641, 53, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (642, 54, N'Karapürçek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (643, 54, N'Söğütlü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (644, 55, N'Ayvacık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (645, 55, N'Kavak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (646, 55, N'LNamek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (647, 55, N'Tekkeköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (648, 55, N'Yakakent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (649, 56, N'Pervari')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (650, 56, N'Şirvan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (651, 57, N'Türkeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (652, 58, N'Akıncılar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (653, 58, N'Altınyayla')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (654, 58, N'Divriği')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (655, 58, N'Doğanşar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (656, 58, N'İmranlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (657, 58, N'Ulaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (658, 59, N'Çerkezköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (659, 59, N'Marmaraereğlisi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (660, 60, N'Zile')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (661, 61, N'Akçaabat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (662, 61, N'Arsin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (663, 61, N'Dernekpazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (664, 61, N'Köprübaşı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (665, 61, N'Maçka')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (666, 61, N'Of')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (667, 61, N'Şalpazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (668, 61, N'Yomra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (669, 63, N'Akçakale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (670, 63, N'Bozova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (671, 63, N'Ceylanpınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (672, 63, N'Harran')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (673, 63, N'Suruç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (674, 64, N'Eşme')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (675, 64, N'Karahallı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (676, 64, N'Ulubey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (677, 65, N'Başkale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (678, 65, N'Çaldıran')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (679, 65, N'Özalp')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (680, 66, N'Boğazlıyan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (681, 66, N'Aydıncık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (682, 66, N'Sorgun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (683, 67, N'Devrek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (684, 67, N'Karadenizereğli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (685, 70, N'Sarıveliler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (686, 71, N'Balışeyh')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (687, 71, N'Yahşihan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (688, 72, N'Kozluk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (689, 73, N'Beytüşşebap')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (690, 73, N'Idil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (691, 75, N'Çıldır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (692, 76, N'Aralık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (693, 76, N'Tuzluca')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (694, 77, N'Çınarcık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (695, 77, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (696, 78, N'Eflani')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (697, 78, N'Eskipazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (698, 78, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (699, 78, N'Safranbolu')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (700, 79, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (701, 80, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (702, 80, N'Toprakkale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (703, 81, N'Cumayeri')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (704, 66, N'Çandır')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (705, 66, N'Çayıralan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (706, 66, N'Çekerek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (707, 67, N'Çaycuma')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (708, 68, N'Eskil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (709, 69, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (710, 70, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (711, 71, N'Bahşili')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (712, 71, N'Çelebi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (713, 71, N'Karakeçili')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (714, 71, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (715, 72, N'Gercüş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (716, 72, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (717, 73, N'Uludere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (718, 74, N'Ulus')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (719, 75, N'Damal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (720, 75, N'Hanak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (721, 75, N'Posof')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (722, 76, N'Karakoyunlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (723, 77, N'Altınova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (724, 77, N'Çiftlikköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (725, 80, N'KNamerli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (726, 81, N'Gölyaka')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (727, 1, N'Gazimagosa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (728, 1, N'Güzelyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (729, 1, N'Pozantı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (730, 1, N'Saimbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (731, 1, N'Sarıçam')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (732, 1, N'Yüreğir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (733, 3, N'Sincanlı(Sinanpaşa)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (734, 4, N'Doğubayazıt(Doğubeyazıt)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (735, 6, N'Altındağ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (736, 6, N'Bala')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (737, 6, N'Beypazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (738, 6, N'Çamlıdere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (739, 6, N'Kalecik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (740, 6, N'Keçiören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (741, 6, N'Kızılcahamam')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (742, 6, N'Şereflikoçhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (743, 6, N'Yenimahalle')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (744, 7, N'Elmalı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (745, 7, N'Gündoğmuş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (746, 7, N'Kemer')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (747, 8, N'Ardanuç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (748, 8, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (749, 8, N'Şavşat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (750, 9, N'DIdim(Yenihisar)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (751, 9, N'Koçarlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (752, 10, N'Dursunbey')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (753, 10, N'Erdek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (754, 10, N'Gönen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (755, 10, N'İvrindi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (756, 10, N'Manyas')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (757, 10, N'Susurluk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (758, 11, N'Osmaneli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (759, 12, N'Karlıova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (760, 12, N'Kiğı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (761, 12, N'Solhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (762, 13, N'Ahlat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (763, 13, N'Tatvan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (764, 14, N'Gerede')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (765, 14, N'Seben')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (766, 14, N'Yeniçağa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (767, 15, N'Gölhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (768, 15, N'Karamanlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (769, 15, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (770, 15, N'Tefenni')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (771, 16, N'Gürsu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (772, 16, N'Harmancık')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (773, 16, N'Kestel')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (774, 17, N'Çan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (775, 17, N'Gökçeada(İmroz)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (776, 17, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (777, 18, N'Korgun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (778, 18, N'Kurşunlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (779, 18, N'Orta')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (780, 19, N'Boğazkale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (781, 19, N'Ortaköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (782, 20, N'Akköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (783, 20, N'Bekilli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (784, 20, N'Bozkurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (785, 20, N'Çameli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (786, 20, N'Çivril')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (787, 20, N'Kale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (788, 21, N'Bağlar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (789, 21, N'Hani')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (790, 21, N'Kocaköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (791, 22, N'Enez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (792, 22, N'Lalapaşa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (793, 23, N'Ağın')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (794, 23, N'Arıcak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (795, 23, N'Karakoçan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (796, 23, N'Keban')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (797, 23, N'Maden')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (798, 24, N'ilıç(iliç)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (799, 24, N'Merkez')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (800, 24, N'Otlukbeli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (801, 24, N'Refahiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (802, 25, N'Hınıs')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (803, 25, N'Pazaryolu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (804, 26, N'Odunpazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (805, 26, N'Seyitgazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (806, 26, N'Sivrihisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (807, 27, N'Araban')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (808, 27, N'Şehitkamil')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (809, 28, N'Çamoluk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (810, 28, N'Espiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (811, 28, N'Piraziz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (812, 28, N'Şebinkarahisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (813, 28, N'Tirebolu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (814, 29, N'Kelkit')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (815, 29, N'Şiran')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (816, 30, N'Şemdinli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (817, 31, N'Altınözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (818, 31, N'Antakya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (819, 31, N'Belen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (820, 31, N'Erzin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (821, 31, N'Kırıkhan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (822, 32, N'Yenişarbademli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (823, 33, N'Mezitli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (824, 33, N'Tarsus')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (825, 33, N'Yenişehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (826, 34, N'Ataşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (827, 34, N'Bahçelievler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (828, 34, N'Beyoğlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (829, 34, N'Çekmeköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (830, 34, N'Güngören')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (831, 34, N'Küçükçekmece')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (832, 34, N'Şile')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (833, 34, N'Ümraniye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (834, 35, N'Bergama')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (835, 35, N'Bornova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (836, 35, N'Karşıyaka')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (837, 35, N'Menderes(Cumaovası)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (838, 35, N'Menemen')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (839, 35, N'Narlıdere')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (840, 35, N'Selçuk')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (841, 36, N'Akyaka')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (842, 36, N'Digor')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (843, 36, N'Sarıkamış')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (844, 36, N'Selim')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (845, 37, N'Şenpazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (846, 38, N'Develi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (847, 38, N'Melikgazi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (848, 38, N'Özvatan(Çukur)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (849, 38, N'Sarıoğlan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (850, 38, N'Yeşilhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (851, 39, N'Pınarhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (852, 40, N'Akçakent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (853, 40, N'Çiçekdağı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (854, 40, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (855, 41, N'Başiskele')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (856, 41, N'Çayırova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (857, 41, N'Gölcük')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (858, 41, N'İzmit')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (859, 41, N'Kandıra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (860, 41, N'Kartepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (861, 42, N'Göksun')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (862, 42, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (863, 42, N'Türkoğlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (864, 43, N'Ahırlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (865, 43, N'Beyşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (866, 43, N'Halkapınar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (867, 43, N'Karatay')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (868, 43, N'Meram')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (869, 43, N'Taşkent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (870, 43, N'Tuzlukçu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (871, 44, N'Altıntaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (872, 44, N'Aslanapa')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (873, 44, N'Simav')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (874, 45, N'Arguvan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (875, 45, N'Doğanyol')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (876, 45, N'Kale')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (877, 46, N'Akhisar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (878, 46, N'Alaşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (879, 46, N'Kırkağaç')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (880, 46, N'Turgutlu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (881, 47, N'MIdyat(Estel)')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (882, 47, N'Nusaybin')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (883, 47, N'Ömerli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (884, 47, N'Savur')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (885, 47, N'Yeşilli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (886, 48, N'Fethiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (887, 48, N'Ula')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (888, 48, N'Yatağan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (889, 49, N'Korkut')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (890, 49, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (891, 50, N'Hacıbektaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (892, 50, N'Ürgüp')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (893, 51, N'Bor')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (894, 51, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (895, 52, N'Çamaş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (896, 52, N'Kabataş')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (897, 52, N'Perşembe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (898, 53, N'Güneysu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (899, 53, N'İkizdere')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (900, 53, N'Pazar')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (901, 54, N'Adapazarı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (902, 54, N'Erenler')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (903, 54, N'Ferizli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (904, 54, N'Kocaali')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (905, 54, N'Taraklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (906, 55, N'Alaçam')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (907, 55, N'Atakum')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (908, 55, N'Bafra')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (909, 56, N'Eruh')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (910, 56, N'Kurtalan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (911, 56, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (912, 57, N'Gerze')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (913, 58, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (914, 58, N'Zara')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (915, 59, N'Hayrabolu')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (916, 59, N'Malkara')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (917, 59, N'Muratlı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (918, 59, N'Saray')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (919, 60, N'Başçiftlik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (920, 60, N'Turhal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (921, 60, N'Yeşilyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (922, 61, N'Araklı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (923, 61, N'Hayrat')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (924, 62, N'Nazımiye')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (925, 62, N'Pertek')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (926, 63, N'Birecik')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (927, 63, N'Hilvan')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (928, 63, N'Viranşehir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (929, 64, N'Banaz')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (930, 64, N'Sivaslı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (931, 65, N'Bahçesaray')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (932, 65, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (933, 66, N'Saraykent')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (934, 66, N'Sarıkaya')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (935, 66, N'Yerköy')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (936, 67, N'Alaplı')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (937, 67, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (938, 68, N'Sarıyahşi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (939, 69, N'Aydıntepe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (940, 69, N'Demirözü')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (941, 70, N'Kazımkarabekir')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (942, 71, N'Sulakyurt')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (943, 72, N'Hasankeyf')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (944, 72, N'Sason')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (945, 73, N'Güçlükonak')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (946, 73, N'Silopi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (947, 74, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (948, 75, N'Göle')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (949, 76, N'Merkez')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (950, 77, N'Termal')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (951, 79, N'Elbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (952, 79, N'Musabeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (953, 79, N'Polateli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (954, 80, N'Bahçe')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (955, 80, N'Düziçi')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (956, 80, N'Hasanbeyli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (957, 80, N'Sumbas')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (958, 81, N'Çilimli')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (959, 81, N'Gümüşova')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (960, 81, N'Merkez')
SET IDENTITY_INSERT [dbo].[Town] OFF
ALTER TABLE [dbo].[Town]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Town_dbo.City_CityId] FOREIGN KEY([CityId])
REFERENCES [dbo].[City] ([Id])
GO
ALTER TABLE [dbo].[Town] CHECK CONSTRAINT [FK_dbo.Town_dbo.City_CityId]
GO
